---

- name: Download CUDA package
  get_url:
    url: {{nvidia_cuda_package_url}}
    dest: /tmp/cuda_install.deb

- name: CUDA | Install downloaded deb package for Ubuntu 16.04
  apt:
    deb: /tmp/cuda_install.deb

- name: Install cuda repo key
  apt_key:
    url: {{nvidia_cuda_key_url}}
    state: present

- name: Install cuda
  apt:
    name: cuda
    state: present
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"

- name: nvidia-runtime-containerd release key is registered
  apt_key:
    url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    state: present

- name: software-properties-common is installed for prerequisite for apt_repository ansible module
  apt:
    name: software-properties-common
    state: present
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"

- name: nvidia-container-runtime apt repositories are registered
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-container-runtime
    state: present
    mode: 0644
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  with_items:
    - 'deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 /'
    - 'deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64 /'
    - 'deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64 /'

- name: Install nvidia-docker2
  apt:
    name: nvidia-docker2
    state: present
  when: not ansible_check_mode
  notify: restart docker
